### ISSUE TITLE
Clean and Sweep

### ISSUE THREAD

**Issue by zeke** [npm/newww#904]
Tasks for @rockbot and @zeke that emerged from our "clean and sweep" spreadsheet audit:

- [ ] review and close all the issues that should be closed AKA gitception
- [ ] web and cli support tools - this is too broad.
- [ ] www user flows: signup, password reset, billing, etc - https://github.com/npm/newww/issues/283, https://github.com/npm/newww/issues/798, https://github.com/npm/newww/issues/884, 
https://github.com/npm/newww/issues/283, 
https://github.com/npm/newww/issues/773, 
https://github.com/npm/newww/issues/694
- [ ] www module cache invalidation after registry events - https://github.com/npm/newww/issues/902
- [ ] Pagination on www profile pages - https://github.com/npm/newww/issues/854
- [ ] better www display of deprecated and unpublished packages - https://github.com/npm/newww/issues/413 and https://github.com/npm/newww/issues/835
- [ ] update AUTHORS - https://github.com/npm/newww/issues/901
- [ ] update README.md - [PR 882](https://github.com/npm/newww/pull/882) staged; awaits a resolution to [#761](https://github.com/npm/newww/issues/761).
- [ ] user-acl client for www - https://github.com/npm/newww/issues/903

**Comment by zeke** [comment]
Moved this content into the milestone description: https://github.com/npm/newww/milestones/Clean%20and%20Sweep
